#!/usr/bin/env python3

import gi
import sys

gi.require_version('Playerctl', '1.0')

from gi.repository import Playerctl, GLib
from subprocess import Popen

player = Playerctl.Player()

prev_info = ""

def on_track_play(player):
    global prev_info

    track_info = 'Playing|{artist}|{title}'.format(artist=player.get_artist(), title=player.get_title())

    if track_info != prev_info:
        prev_info = track_info
        print(track_info)
        sys.stdout.flush()

def on_track_pause(player):
    global prev_info

    track_info = 'Paused|{artist}|{title}'.format(artist=player.get_artist(), title=player.get_title())

    if track_info != prev_info:
        prev_info = track_info
        print(track_info)
        sys.stdout.flush()

def on_track_stop(player):
    global prev_info

    track_info = 'Stopped'

    if track_info != prev_info:
        prev_info = track_info
        print(track_info)
        sys.stdout.flush()

if player.get_title() is not None:
    print player.get_status()

player.connect('play', on_track_play)
player.connect('pause', on_track_pause)
player.connect('stop', on_track_stop)

GLib.MainLoop().run()
